# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Split a string into codons
#'
#' @author Boris Steipe, \email{boris.steipe@@utoronto.ca}
#' ORCID: 0000-0002-1134-6758
#' License: (c) Author (2018) + MIT
#' Date: 2018-12-31
#' @param cDNA (char) A single string
#' @return (char) a vector of triplets
#' @examples
#' # Split a string into codons
#' cpp_codonSplitCpp("ATGAAATGA")
#' @export
cpp_codonSplitCpp <- function(cDNA) {
    .Call('_rptPlus_cpp_codonSplitCpp', PACKAGE = 'rptPlus', cDNA)
}

#' @export
initializeMatrix <- function(initVal, ROW_SIZE, COL_SIZE) {
    .Call('_rptPlus_initializeMatrix', PACKAGE = 'rptPlus', initVal, ROW_SIZE, COL_SIZE)
}

#' @export
getseqSimMat <- function(seq1, seq2, Match, MisMatch, s) {
    invisible(.Call('_rptPlus_getseqSimMat', PACKAGE = 'rptPlus', seq1, seq2, Match, MisMatch, s))
}

meanC <- function(x, s) {
    .Call('_rptPlus_meanC', PACKAGE = 'rptPlus', x, s)
}

TestMatrixParsing <- function() {
    .Call('_rptPlus_TestMatrixParsing', PACKAGE = 'rptPlus')
}

